language: node_js
node_js:
  - "10.18.1"

cache:
  directories:
    - node_modules

after_success:
  - npm test

deploy:
  - provider: script
    script: npm run build
    skip_cleanup: true
    on:
      branch: master
