openapi: 3.0.0
info:
  title: event-broker
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /pubsub/adapter:
    get:
      summary: Pub/Sub Adapter Get
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  adapter:
                    $ref: '#/components/schemas/Adapter'
      operationId: get-adapter
      requestBody:
        content:
          application/json:
            schema:
              type: object
      tags:
        - Rest
    post:
      summary: Pub/Sub Adapter Set
      operationId: post-adapter
      responses:
        '204':
          description: No Content
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                adapter:
                  $ref: '#/components/schemas/Adapter'
        description: ''
      tags:
        - Rest
    parameters: []
  /event:
    post:
      summary: Publish Event
      operationId: post-event
      responses:
        '204':
          description: No Content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublishEventRequest'
      tags:
        - Rest
components:
  schemas:
    PublishEventRequest:
      title: PublishEventRequest
      type: object
      properties:
        topic:
          type: string
        payload:
          oneOf: [number, object, string]
      x-tags:
        - Models
    SetAdapterRequest:
      title: SetAdapterRequest
      type: object
      properties:
        adapter:
          $ref: '#/components/schemas/Adapter'
      x-tags:
        - Models
    Adapter:
      type: string
      enum:
        - redis
        - kafka
      x-tags:
        - Models
  securitySchemes: {}
