openapi: 3.0.0
info:
  title: mobile_platform
  version: '1.0'
  contact:
    name: Zachary Quintana
    url: 'https://github.com/zquintana'
    email: zach.quintana@gmail.com
servers:
  - url: 'http://localhost:3000'
paths:
  '/consume/{providerCode}':
    parameters:
      - schema:
          type: string
        name: providerCode
        in: path
        required: true
    post:
      summary: Consume a Message
      operationId: consume
      responses:
        '202':
          description: Accepted
          headers:
            Location:
              schema:
                type: string
      tags:
        - API
      description: ''
  /messages:
    post:
      summary: Send a New Message
      operationId: post-message
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResult'
              examples: {}
        '406':
          description: Not Acceptable
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMessageRequest'
      tags:
        - API
  '/messages/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get Messages for a Number
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
      operationId: get-message
      description: ''
      tags:
        - API
  /numbers:
    get:
      summary: Search Available Numbers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PhoneNumber'
        '400':
          description: Bad Request
        '409':
          description: Conflict
      operationId: get-numbers
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchNumbersRequest'
      tags:
        - API
  /provision:
    post:
      summary: Provision a Number
      operationId: provision
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProvisionRequest'
      tags:
        - API
    delete:
      summary: Release a Number
      operationId: release
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReleaseNumberRequest'
        description: ''
      tags:
        - API
  /_internal_/health:
    get:
      summary: Health Check
      responses:
        '200':
          description: OK
      operationId: get-health
      description: ''
      tags:
        - Health Check
components:
  schemas:
    MessageResult:
      title: MessageResult
      type: object
      properties:
        id:
          type: string
      x-tags:
        - Models
    Message:
      title: Message
      type: object
      x-tags:
        - Models
      properties:
        id:
          type: string
        to:
          type: string
        from:
          type: string
        body:
          type: string
        direction:
          $ref: '#/components/schemas/Direction'
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
    Attachment:
      title: Attachment
      type: object
      x-tags:
        - Models
      properties:
        id:
          type: string
        uri:
          type: string
          format: uri
    PhoneNumber:
      title: PhoneNumber
      type: object
      properties:
        number:
          type: string
        formatted:
          type: string
      x-tags:
        - Models
    NewMessageRequest:
      title: NewMessageRequest
      type: object
      properties:
        from:
          type: string
        to:
          type: string
        body:
          type: string
        attachments:
          type: array
          items:
            type: string
      x-tags:
        - Request
    SearchNumbersRequest:
      title: SearchNumbersRequest
      type: object
      x-tags:
        - Request
      properties:
        country:
          type: string
        areaCode:
          type: string
        provider:
          type: string
      required:
        - country
        - provider
    ProvisionRequest:
      title: ProvisionRequest
      type: object
      x-tags:
        - Request
      properties:
        provider:
          type: string
        number:
          type: string
    ReleaseNumberRequest:
      title: ReleaseNumberRequest
      type: object
      properties:
        number:
          type: string
      x-tags:
        - Request
    Direction:
      type: string
      enum:
        - inbound
        - outbound
        - unknown
      x-tags:
        - Models
      description: ''
  securitySchemes:
    JWT_Token:
      type: http
      scheme: bearer
      description: JWT Token
security:
  - JWT Token: []
