openapi: 3.0
info:
    title: Zingle Url Shortner
    description: Shortens URLs
    contact:
        name: API Support
        url: http://www.zingle.me
    version: 1.0.0

paths:
    /v1:
        post:
            description: Shorten a single URL
            operationId: shorten
            tags: [v1]
            responses:
                '200':
                    description: Creates a shortened URL
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ShortUrl'

                '400':
                    description: Failed to create urls
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'

            requestBody:
                content:
                    '*/*':
                        schema:
                            $ref: '#/components/schemas/shortenRequest'



    /v1/bulk:
        post:
            description: Shorten a bulk URLs
            operationId: shortenBulk
            tags: [v1]
            responses:
                '200':
                    description: Bulk creates a shortened URLs
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/ShortUrl'

                '400':
                    description: Failed to create urls
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'

            requestBody:
                content:
                    '*/*':
                        schema:
                            $ref: '#/components/schemas/BulkShortenRequest'

    /v1/replace:
        post:
            description: Replace targetUrls in string
            operationId: replace
            tags: [v1]
            responses:
                '200':
                    description: Replaced urls in string
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/ReplacedText'

                '400':
                    description: Failed to create urls
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'

            requestBody:
                content:
                    '*/*':
                        schema:
                            $ref: '#/components/schemas/ReplaceRequest'


    /_internal_/health:
        get:
            operationId: getHealthCheck
            description: Checks health of service
            responses:
                '200':
                    description: 'Everything is good'

                '417':
                    description: 'Database connection failed'

components:
    schemas:
        ShortenRequest:
            type: object
            properties:
                targetUrl:
                    type: string
                vendor:
                    $ref: '#/components/schemas/Vendor'

        BulkShortenRequest:
            type: object
            properties:
                targetUrls:
                    type: array
                vendor:
                    $ref: '#/components/schemas/Vendor'

        ReplaceRequest:
            type: object
            properties:
                targetUrls:
                    type: array
                vendor:
                    $ref: '#/components/schemas/Vendor'
                text:
                    type: string
                preferVedor:
                    type: boolean

        Vendor:
            type: object
            properties:
                code:
                    type: string
                token:
                    type: string

        Error:
            type: object
            properties:
                error:
                    type: string

        ShortUrl:
            type: object
            properties:
                url:
                    type: string
                targetUrl:
                    type: string
                vendorUrl:
                    type: object
                    $ref: '#/components/schemas/VendorUrl'


        ReplacedText:
            type: object
            properties:
                text:
                    type: string
                originalText:
                    type: string
                shortUrls:
                    type: array
                    items:
                        $ref: '#/components/schemas/ShortUrl'

        VendorUrl:
            type: object
            properties:
                vendor:
                    type: string
                url:
                    type: string

    securitySchemes:
        jwt:
            type: http
            scheme: bearer
            bearerFormat: JWT

servers:
    - url: http://127.0.0.1:{port}
      description: Local development server
      variables:
          port:
              default: 8000
    - url: https://zngl.me
      description: Production server
